name: 'applyluma_dw'
version: '1.0.0'
config-version: 2

profile: 'applyluma'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

target-path:  "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  applyluma_dw:
    staging:
      +materialized: view
      +tags: ["staging"]
    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]
    marts:
      +materialized: table
      +tags: ["marts"]
