export const CV_TIPS: string[] = [
  "Recruiters spend about 7 seconds on a first pass — put your strongest, most relevant experience in the top third of the page.",
  "Mirror the exact keywords from the job description where they genuinely apply — most ATS systems match on literal phrasing, not synonyms.",
  "Quantify your impact wherever possible. 'Improved performance' says less than 'reduced load time by 40%.'",
  "Avoid graphics, tables, and text boxes in ATS-bound resumes — many parsers can't read them and will scramble your content.",
  "One page is a good target for under 10 years of experience. Recruiters won't hold a well-organized two-pager against you if the content earns it.",
  "Lead bullet points with strong action verbs — 'Built,' 'Led,' 'Reduced,' 'Shipped' — rather than passive phrases like 'Responsible for.'",
  "Tailor your summary line to the specific role. A generic summary is often the first thing a recruiter skims past.",
  "List skills you can actually discuss in an interview. Fabricated or exaggerated skills tend to surface fast under questioning.",
  "Consistent formatting (fonts, spacing, date formats) signals attention to detail before a recruiter reads a single word.",
  "Save and submit as PDF unless the application explicitly asks for Word — PDFs preserve formatting across systems.",
  "Use a clean, standard file name like FirstName_LastName_Resume.pdf — recruiters often manage dozens of files at once.",
  "Group related skills into categories (e.g. 'Languages,' 'Cloud & Infra') rather than one long unsorted list — it reads faster.",
  "Recent, relevant experience matters more than a complete chronological history. It's fine to compress or omit older, unrelated roles.",
  "Numbers catch the eye faster than adjectives. Try to attach a metric to at least one bullet per role.",
  "If you're changing careers or fields, a short 'relevant skills' section near the top can bridge the gap for a skimming recruiter.",
  "Typos and inconsistent verb tense are among the most common reasons resumes get filtered out early — always do a final read-through.",
  "Contact info should be complete and easy to find: name, email, phone, and location (city/region is usually enough).",
  "LinkedIn and portfolio links are worth including if they're active and up to date — dead or stale links can hurt more than help.",
  "Match your resume's job titles to industry-standard terms when accurate, so both ATS and humans recognize your role level.",
  "Soft skills (communication, leadership) land better shown through an example than stated as a bullet point on their own.",
  "For technical roles, listing specific tools and versions (e.g. 'PostgreSQL,' 'FastAPI') is often more useful to a screener than broad categories.",
  "A tailored resume for one role will almost always outperform a single resume sent everywhere — small adjustments compound.",
  "Gaps in employment are increasingly normal and rarely need over-explaining on the resume itself — save context for the interview if asked."
];
